/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GramineJni_gramine_jni */

#ifndef _Included_GramineJni_gramine_jni
#define _Included_GramineJni_gramine_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GramineJni_gramine_jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GramineJni_gramine_1jni_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
