# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  configuration: documents/readthedoc/docs/source/conf.py

python:
  install:
    - requirements: documents/readthedoc/requirements.txt
