[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata-qemu-tdx-linux]
runtime_type = "io.containerd.kata-qemu-tdx.v2"
runtime_path = "/opt/coco/prebuilt/asterinas-coco/containerd-shim-kata-v2"
pod_annotations = ["io.katacontainers.*"]
container_annotations = []
privileged_without_host_devices = true
privileged_without_host_devices_all_devices_allowed = false
cgroup_writable = false
base_runtime_spec = ""
cni_conf_dir = ""
cni_max_conf_num = 0
snapshotter = "nydus"
sandboxer = ""
io_type = ""

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata-qemu-tdx-linux.options]
ConfigPath = "/opt/coco/config/configuration-qemu-tdx-linux.toml"

[plugins."io.containerd.cri.v1.images".runtime_platforms.kata-qemu-tdx-linux]
platform = ""
snapshotter = "nydus"
