# Copyright (c) 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV STRICT_MODE=false

WORKDIR /app

COPY adapters/OpenViking/examples/openviking_service.py /app/openviking_service.py

EXPOSE 8010

CMD ["python3", "/app/openviking_service.py", "--serve"]