# Copyright 2021 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: gramine-tf-serving

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: gramine-tf-serving-service
  name: gramine-tf-serving-service
  namespace: gramine-tf-serving
spec:
  type: NodePort # LoadBalancer ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 30500
  selector:
    app: gramine-tf-serving-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramine-tf-serving-deployment
  namespace: gramine-tf-serving
spec:
  selector:
    matchLabels:
      app: gramine-tf-serving-app
  replicas: 1
  template:
    metadata:
      labels:
        app: gramine-tf-serving-app
    spec:
      containers:
      - name: gramine-tf-serving-container
        image: gramine_tf_serving:{YOUR TAG}
        imagePullPolicy: Never
        env:
        - name: model_name
          value: "resnet50-v15-fp32"
        - name: file_system_poll_wait_seconds
          value: "5"
        - name: "enable_batching"
          value: "false"
        - name: rest_api_num_threads
          value: "64"
        - name: session_parallelism
          value: "0"
        - name: intra_op_parallelism
          value: "32"
        - name: inter_op_parallelism
          value: "32"
        - name: OMP_NUM_THREADS
          value: "32"
        - name: MKL_NUM_THREADS
          value: "32"
        - name: KMP_BLOCKTIME
          value: "0"
        - name: ssl_config_file
          value: "/ssl.cfg"
        - name: SGX
          value: "1"
        - name: ISGX_DRIVER_PATH
          value: "/gramine/driver/driver/linux/include"
        - name: WORK_BASE_PATH
          value: "/gramine/CI-Examples/tensorflow-serving-cluster/tensorflow-serving"
        - name: http_proxy
          value: ""
        - name: https_proxy
          value: ""
        - name: no_proxy
          value: ""
        ports:
        - name: grpc
          containerPort: 8500
        volumeMounts:
        - name: sgx-path
          mountPath: /dev/sgx
        - name: model-path
          mountPath: /gramine/CI-Examples/tensorflow-serving-cluster/tensorflow-serving/models/resnet50-v15-fp32
        - name: ssl-path
          mountPath: /gramine/CI-Examples/tensorflow-serving-cluster/tensorflow-serving/ssl.cfg
        - name: asem-pgramine
          mountPath: /var/run/aesmd/aesm
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "32"
          requests:
            cpu: "32"
      volumes:
      - name: sgx-path
        hostPath:
          path: /dev/sgx
      - name: model-path
        hostPath:
          path: <Your gramine repository>/CI-Examples/tensorflow-serving-cluster/tensorflow_serving/models/resnet50-v15-fp32
      - name: ssl-path
        hostPath:
          path: <Your gramine repository>/CI-Examples/tensorflow-serving-cluster/tensorflow_serving/ssl_configure/ssl.cfg
      - name: asem-path
        hostPath:
          path: /var/run/aesmd/aesm
