/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GramineJni_gramine_jni */

#ifndef _Included_GramineJni_gramine_jni
#define _Included_GramineJni_gramine_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GramineJni_gramine_jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GramineJni_gramine_1jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GramineJni_gramine_jni
 * Method:    get_key
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_GramineJni_gramine_1jni_get_1key
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     GramineJni_gramine_jni
 * Method:    get_file_2_buff
 * Signature: ([B[BJ[J)I
 */
JNIEXPORT jint JNICALL Java_GramineJni_gramine_1jni_get_1file_12_1buff
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jlong, jlongArray);

/*
 * Class:     GramineJni_gramine_jni
 * Method:    get_file_2_file
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_GramineJni_gramine_1jni_get_1file_12_1file
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
